export type FreestyleCuratedCategory = {
  title: string;
  names: string[];
};

/** Plain ASCII names used by the Surprise Me button. */
export const FREESTYLE_SURPRISE_BASE_NAMES = [
  "Shadow",
  "Phoenix",
  "Rebel",
  "Nova",
  "Viper",
  "Storm",
  "Blaze",
  "Ghost",
  "Ace",
  "Fury",
  "Savage",
  "Rogue",
  "Ember",
  "Cipher",
  "Titan",
  "Luna",
  "Rose",
  "Pixie",
  "Cherry",
  "Blossom",
  "Angel",
  "Honey",
  "Star",
  "Dream",
  "Sky",
  "Zen",
  "Neo",
  "Rex",
  "Fox",
  "Jet",
  "Kai",
  "Lux",
  "Onyx",
  "Rio",
  "Zed",
  "Ash",
  "Ice",
  "Max",
  "Pro",
  "King",
] as const;

export const FREESTYLE_CURATED_NAMES: FreestyleCuratedCategory[] = [
  {
    title: "Gamer nicknames",
    names: [
      "꧁𝓢𝓱𝓪𝓭𝓸𝔀𝓗𝓾𝓷𝓽𝓮𝓻꧂",
      "★彡𝓝𝓲𝓰𝓱𝓽𝓢𝓽𝓪𝓵𝓴𝓮𝓻彡★",
      "🔥𝕻𝖗𝖔𝕲𝖆𝖒𝖊𝖗🔥",
      "꧁☬𝕯𝖊𝖆𝖙𝖍𝕾𝖍𝖔𝖙☬꧂",
      "☠𝓢𝓷𝓲𝓹𝓮𝓻𝓔𝓵𝓲𝓽𝓮☠",
      "꧁༺𝕽𝖆𝖌𝖊𝕸𝖔𝖉𝖊༻꧂",
      "★彡𝓖𝓪𝓶𝓮𝓞𝓿𝓮𝓻彡★",
      "꧁𝓚𝓲𝓵𝓵𝓜𝓪𝓼𝓽𝓮𝓻꧂",
      "☬𝕯𝖆𝖗𝖐𝕷𝖊𝖌𝖊𝖓𝖉☬",
      "༒︎𝓣𝓸𝔁𝓲𝓬𝓟𝓻𝓸༒︎",
    ],
  },
  {
    title: "Attitude nicknames",
    names: [
      "꧁𝕾𝖆𝖛𝖆𝖌𝖊꧂",
      "☬𝓡𝓮𝓫𝓮𝓵𝓚𝓲𝓷𝓰☬",
      "★彡𝔹𝕒𝕕𝔹𝕠𝕪彡★",
      "꧁༺𝕯𝖔𝖓𝖙𝕮𝖆𝖗𝖊༻꧂",
      "♛𝓢𝓲𝓵𝓮𝓷𝓽𝓚𝓲𝓵𝓵𝓮𝓻♛",
      "꧁☠𝕭𝖑𝖔𝖔𝖉𝕷𝖔𝖗𝖉☠꧂",
      "☬𝕯𝖊𝖆𝖉𝕷𝖞☬",
      "꧁𝓣𝓱𝓮𝓑𝓸𝓼𝓼꧂",
      "★彡𝓝𝓸𝓜𝓮𝓻𝓬𝔂彡★",
      "༒︎𝕯𝖆𝖗𝖐𝕾𝖔𝖚𝖑༒︎",
    ],
  },
  {
    title: "Cute nicknames for girls",
    names: [
      "✿𝓡𝓸𝓼𝓮𝓠𝓾𝓮𝓮𝓷✿",
      "꧁💖𝓛𝓾𝓷𝓪𝓖𝓲𝓻𝓵💖꧂",
      "♛𝒫𝓇𝒾𝓃𝒸𝑒𝓈𝓈♛",
      "🌸𝓢𝓪𝓴𝓾𝓻𝓪🌸",
      "✧𝒜𝓂𝒷𝑒𝓇𝒮𝓉𝒶𝓇✧",
      "꧁༺𝒮𝓌𝑒𝑒𝓉ℋ𝑒𝒶𝓇𝓉༻꧂",
      "✿𝓜𝓸𝓸𝓷𝓛𝓲𝓰𝓱𝓽✿",
      "♚𝒞𝒽𝑒𝓇𝓇𝓎𝐵𝓁𝑜𝓈𝓈♚",
      "𝓑𝓵𝓸𝓼𝓼𝓸𝓶𝓖𝓲𝓻𝓵",
      "✿𝓓𝓲𝓪𝓶𝓸𝓷𝓭𝓓𝓸𝓵𝓵✿",
    ],
  },
  {
    title: "Short 1-word nicknames",
    names: [
      "𝕯𝖆𝖗𝖐",
      "ᴋɪɴɢ",
      "☬𝓐𝓒𝓔☬",
      "꧁𝓟𝓻𝓸꧂",
      "ℭ𝕽𝕴𝕸",
      "♛𝓖𝓞𝓓♛",
      "𝕹𝖊𝖔",
      "☠𝓓𝓔𝓥☠",
      "ᴀᴄᴇ",
      "彡ℤ𝓮𝓷彡",
    ],
  },
];
